// Indices for states etc

// NB: Indices fixed for C indexing

#define index_V 0
#define index_mNa 1
#define index_hNa 2
#define index_jNa 3
#define index_Nai 4
#define index_Ki 5
#define index_Cai 6
#define index_CaNSR 7
#define index_xKs 8
#define index_LTRPNCa 9
#define index_HTRPNCa 10
#define index_C0Kv43 11
#define index_C1Kv43 12
#define index_C2Kv43 13
#define index_C3Kv43 14
#define index_OKv43 15
#define index_CI0Kv43 16
#define index_CI1Kv43 17
#define index_CI2Kv43 18
#define index_CI3Kv43 19
#define index_OIKv43 20
#define index_C0Kv14 21
#define index_C1Kv14 22
#define index_C2Kv14 23
#define index_C3Kv14 24
#define index_OKv14 25
#define index_CI0Kv14 26
#define index_CI1Kv14 27
#define index_CI2Kv14 28
#define index_CI3Kv14 29
#define index_OIKv14 30
#define index_CaTOT 31
#define index_C1Herg 32
#define index_C2Herg 33
#define index_C3Herg 34
#define index_OHerg 35
#define index_IHerg 36
#define index_CytCaMKII_I 37
#define index_CytCaMKII_B 38
#define index_CytCaMKII_P 39
#define index_CytCaMKII_T 40
#define index_CytCaMKII_A 41
#define index_CytCaMKII_C 42
#define index_CytCaMKII_U 43
#define index_FracPLB_P 44

#define index_CaSSavg 0
#define index_CaJSRavg 1
#define index_JRyRtot 2
#define index_PRyR_Open 3
#define index_PRyR_ready 4
#define index_PNorm_Mode 5
#define index_PnotVinact 6
#define index_PLType_Open 7
#define index_CaTOT2 8
#define index_PIto2_Open 9
#define index_CaJSRtot 10
#define index_CaSStot 11
#define index_CaMKII_Act 12
#define index_LCCP0 13
#define index_LCCP1 14
#define index_LCCP2 15
#define index_LCCP3 16
#define index_CaMKII_Phosph 17
#define index_Mode2Open 18
#define index_RyRP0 19
#define index_RyRP1 20
#define index_RyRP2 21

#define index_INa 0
#define index_IKr 1
#define index_IKs 2
#define index_Ito1 3
#define index_IK1 4
#define index_IKp 5
#define index_INaCa 6
#define index_INaK 7
#define index_IpCa 8
#define index_ICab 9
#define index_INab 10
#define index_ICa 11
#define index_JDHPR 12
#define index_Jup 13
#define index_Jtrpn 14
#define index_Jtr 15
#define index_Jxfer 16
#define index_IKv43 17
#define index_IKv14 18
#define index_IKv14_K 19
#define index_IKv14_Na 20
#define index_Ito2 21
#define index_Istim 22
#define index_Itot 23

#define index_frudep_V 0
#define index_frudep_Cai 1
#define index_frudep_CaNSR 2

#define index_frustates_CaJSR 0

#define index_LCC_states 0
#define index_LCC_Vinact 1
